sudo: required
dist: trusty
sudo: true

cache:
  apt: true

before_install:
  # Update apt-get
  - sudo apt-get update -qq
  # Install Vagrant 1.9.1
  # Todo: install from a package repository, not from a hardcoded URL.
  - curl -O https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb

install:
  - cp settings.yml settings.local.yml
  - "sed 's/hostname: \"\"/hostname: \"travis\"/g' -i ./settings.local.yml"

script:
  - vagrant status
