sudo: required
dist: trusty
sudo: true

cache:
  apt: true

before_install:
  - sudo apt-get install virtualbox
  - sudo apt-get install virtualbox-dkms
  - sudo apt-get install vagrant

script:
  - vagrant up
