---
- name: Install Apache2 web server
  apt:
    name: apache2
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
      - rewrite
  notify:
    - Restart Apache2 web server

- name: Deactivate default virtual host.
  command: a2dissite 000-default
  notify:
    - Restart Apache2 web server

- name: Deactivate default virtual SSL host.
  command: a2dissite default-ssl
  notify:
    - Restart Apache2 web server
