---
# Default Vagrant, VirtualBox and Ansible settings.

# Vagrant configuration.
box:
  name: "default"
  ip_address: "192.168.192.168"

# VirtualBox configuration.
virtualbox:
  cpus: 2
  memory: 1024
  cpuexecutioncap: 100
